# Site settings
title: UI Toolkit
email: kwhaler@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  User interface toolkits are helpful for ensuring consistent quality in your web software products and encouraging rapid prototyping in agile software environments.
baseurl: "/btc-toolkit" # the subpath of your site, e.g. /blog/
url: "http://kwhaler.github.io" # the base hostname & protocol for your site
twitter_username: kwhaler
github_username:  kwhaler

# Build settings
markdown: kramdown
